package model;
// Generated Feb 22, 2017 4:42:55 PM by Hibernate Tools 4.3.1



/**
 * Friends generated by hbm2java
 */
public class Friends  implements java.io.Serializable {


     private FriendsId id;
     private User userByUserId;
     private User userByFriendId;
     private byte status;

    public Friends() {
    }

    public Friends(FriendsId id, User userByUserId, User userByFriendId, byte status) {
       this.id = id;
       this.userByUserId = userByUserId;
       this.userByFriendId = userByFriendId;
       this.status = status;
    }
   
    public FriendsId getId() {
        return this.id;
    }
    
    public void setId(FriendsId id) {
        this.id = id;
    }
    public User getUserByUserId() {
        return this.userByUserId;
    }
    
    public void setUserByUserId(User userByUserId) {
        this.userByUserId = userByUserId;
    }
    public User getUserByFriendId() {
        return this.userByFriendId;
    }
    
    public void setUserByFriendId(User userByFriendId) {
        this.userByFriendId = userByFriendId;
    }
    public byte getStatus() {
        return this.status;
    }
    
    public void setStatus(byte status) {
        this.status = status;
    }




}


