package model;
// Generated Feb 22, 2017 4:42:55 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Post generated by hbm2java
 */
public class Post  implements java.io.Serializable {


     private Integer postId;
     private Thread thread;
     private User user;
     private String message;
     private Date postDateTime;
     private Date updateDateTime;

    public Post() {
    }

    public Post(Thread thread, User user, String message, Date postDateTime, Date updateDateTime) {
       this.thread = thread;
       this.user = user;
       this.message = message;
       this.postDateTime = postDateTime;
       this.updateDateTime = updateDateTime;
    }
   
    public Integer getPostId() {
        return this.postId;
    }
    
    public void setPostId(Integer postId) {
        this.postId = postId;
    }
    public Thread getThread() {
        return this.thread;
    }
    
    public void setThread(Thread thread) {
        this.thread = thread;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    public Date getPostDateTime() {
        return this.postDateTime;
    }
    
    public void setPostDateTime(Date postDateTime) {
        this.postDateTime = postDateTime;
    }
    public Date getUpdateDateTime() {
        return this.updateDateTime;
    }
    
    public void setUpdateDateTime(Date updateDateTime) {
        this.updateDateTime = updateDateTime;
    }




}


