package model;
// Generated Feb 22, 2017 4:42:55 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Thread generated by hbm2java
 */
public class Thread  implements java.io.Serializable {


     private Integer threadId;
     private Discussion discussion;
     private User user;
     private String title;
     private Date publishDateTime;
     private byte isPinned;
     private byte categoryType;
     private Set<Post> posts = new HashSet<Post>(0);

    public Thread() {
    }

	
    public Thread(Discussion discussion, User user, String title, Date publishDateTime, byte isPinned, byte categoryType) {
        this.discussion = discussion;
        this.user = user;
        this.title = title;
        this.publishDateTime = publishDateTime;
        this.isPinned = isPinned;
        this.categoryType = categoryType;
    }
    public Thread(Discussion discussion, User user, String title, Date publishDateTime, byte isPinned, byte categoryType, Set<Post> posts) {
       this.discussion = discussion;
       this.user = user;
       this.title = title;
       this.publishDateTime = publishDateTime;
       this.isPinned = isPinned;
       this.categoryType = categoryType;
       this.posts = posts;
    }
   
    public Integer getThreadId() {
        return this.threadId;
    }
    
    public void setThreadId(Integer threadId) {
        this.threadId = threadId;
    }
    public Discussion getDiscussion() {
        return this.discussion;
    }
    
    public void setDiscussion(Discussion discussion) {
        this.discussion = discussion;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    public Date getPublishDateTime() {
        return this.publishDateTime;
    }
    
    public void setPublishDateTime(Date publishDateTime) {
        this.publishDateTime = publishDateTime;
    }
    public byte getIsPinned() {
        return this.isPinned;
    }
    
    public void setIsPinned(byte isPinned) {
        this.isPinned = isPinned;
    }
    public byte getCategoryType() {
        return this.categoryType;
    }
    
    public void setCategoryType(byte categoryType) {
        this.categoryType = categoryType;
    }
    public Set<Post> getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set<Post> posts) {
        this.posts = posts;
    }




}


