package model;
// Generated Feb 23, 2017 9:05:54 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private Integer userId;
     private Discussion discussion;
     private String username;
     private String password;
     private String email;
     private String imageUrl;
     private String description;
     private String name;
     private String country;
     private String province;
     private String city;
     private Date joinDate;
     private Set<Post> posts = new HashSet<Post>(0);
     private Set<Thread> threads = new HashSet<Thread>(0);
     private Set<Friends> friendsesForUserId = new HashSet<Friends>(0);
     private Set<Friends> friendsesForFriendId = new HashSet<Friends>(0);

    public User() {
    }

	
    public User(String username, String password, String email, String imageUrl, String description, String name, String country, String province, String city, Date joinDate) {
        this.username = username;
        this.password = password;
        this.email = email;
        this.imageUrl = imageUrl;
        this.description = description;
        this.name = name;
        this.country = country;
        this.province = province;
        this.city = city;
        this.joinDate = joinDate;
    }
    public User(Discussion discussion, String username, String password, String email, String imageUrl, String description, String name, String country, String province, String city, Date joinDate, Set<Post> posts, Set<Thread> threads, Set<Friends> friendsesForUserId, Set<Friends> friendsesForFriendId) {
       this.discussion = discussion;
       this.username = username;
       this.password = password;
       this.email = email;
       this.imageUrl = imageUrl;
       this.description = description;
       this.name = name;
       this.country = country;
       this.province = province;
       this.city = city;
       this.joinDate = joinDate;
       this.posts = posts;
       this.threads = threads;
       this.friendsesForUserId = friendsesForUserId;
       this.friendsesForFriendId = friendsesForFriendId;
    }
   
    public Integer getUserId() {
        return this.userId;
    }
    
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
    public Discussion getDiscussion() {
        return this.discussion;
    }
    
    public void setDiscussion(Discussion discussion) {
        this.discussion = discussion;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public String getProvince() {
        return this.province;
    }
    
    public void setProvince(String province) {
        this.province = province;
    }
    public String getCity() {
        return this.city;
    }
    
    public void setCity(String city) {
        this.city = city;
    }
    public Date getJoinDate() {
        return this.joinDate;
    }
    
    public void setJoinDate(Date joinDate) {
        this.joinDate = joinDate;
    }
    public Set<Post> getPosts() {
        return this.posts;
    }
    
    public void setPosts(Set<Post> posts) {
        this.posts = posts;
    }
    public Set<Thread> getThreads() {
        return this.threads;
    }
    
    public void setThreads(Set<Thread> threads) {
        this.threads = threads;
    }
    public Set<Friends> getFriendsesForUserId() {
        return this.friendsesForUserId;
    }
    
    public void setFriendsesForUserId(Set<Friends> friendsesForUserId) {
        this.friendsesForUserId = friendsesForUserId;
    }
    public Set<Friends> getFriendsesForFriendId() {
        return this.friendsesForFriendId;
    }
    
    public void setFriendsesForFriendId(Set<Friends> friendsesForFriendId) {
        this.friendsesForFriendId = friendsesForFriendId;
    }




}


